
### Universidad Autónoma de Chihuahua

#### Facultad de ingeniería

##### Ingeniería en Ciencias de la Computación


## Curso de Machine Learning
---


# Trabaja con iris

##### **Trabajo de**: Adrian A. González Domínguez

###### **Matrícula**: 359834

##### **Asesor**: Manuel Alberto Chavez Salcido

##### *7 de septiembre de 2024*

### Librerias de codigo

In [13]:
import numpy
from scipy.linalg import lu
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer

### Cargar datos

In [14]:
iris = load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)
data.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

### Normalizar

In [17]:
normalizer = Normalizer()
normalized_data = normalizer.fit_transform(data)
normalized_data_df = pd.DataFrame(normalized_data, columns=iris.feature_names)
normalized_data_df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.803773          0.551609           0.220644          0.031521
1           0.828133          0.507020           0.236609          0.033801
2           0.805333          0.548312           0.222752          0.034269
3           0.800030          0.539151           0.260879          0.034784
4           0.790965          0.569495           0.221470          0.031639

### Estandarizar

In [19]:
standarizer = StandardScaler()
standarized_data = standarizer.fit_transform(data)
standarized_data_df = pd.DataFrame(standarized_data, columns=iris.feature_names)
standarized_data_df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444